.PHONY: run help

run:
	python3.13 -m http.server 80

help:
	@echo "Available commands:"
	@echo "  make run        - Run the frontend service using python3.13"
	@echo "  make help       - Show this help message"