name: Backend CI - Build and Test

on:
  push:
    branches: [ magic ]
  pull_request:
    branches: [ magic ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: |
        cd backend
        ./mvnw clean verify

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/target/surefire-reports/
        if-no-files-found: error 