name: Backend CI - Build and Test

on:
  push:
    branches: [ magic ]
  pull_request:
    branches: [ magic ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      id: build
      run: |
        cd backend
        ./mvnw clean test verify -Dmaven.test.failure.ignore=false

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: backend/target/surefire-reports/
        if-no-files-found: error 